import Head from "next/head";
import styles from "../styles/Home.module.css";
import Feed from "../components/Feed";
import { useRouter } from "next/router";
import { useContext } from "react";
import { AuthContext } from "../context/auth";
export default function Home() {
  const { user } = useContext(AuthContext);
  const Redirect = () => {
    const route = useRouter();
    route.push("/login");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user?.uid ? <Feed /> : <Redirect />}
    </div>
  );
}
